// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DashboardServiceClient is the client API for DashboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DashboardServiceClient interface {
	// 获取核心指标
	GetCoreIndicators(ctx context.Context, in *GetCoreIndicatorsRequest, opts ...grpc.CallOption) (*GetCoreIndicatorsResponse, error)
	// 获取业绩表现
	GetPerformance(ctx context.Context, in *GetPerformanceRequest, opts ...grpc.CallOption) (*GetPerformanceResponse, error)
	// 获取客户分布
	GetCustomerDistribution(ctx context.Context, in *GetCustomerDistributionRequest, opts ...grpc.CallOption) (*GetCustomerDistributionResponse, error)
	// 获取客户行为
	GetCustomerBehavior(ctx context.Context, in *GetCustomerBehaviorRequest, opts ...grpc.CallOption) (*GetCustomerBehaviorResponse, error)
	// 获取股票交易
	GetStockTrade(ctx context.Context, in *GetStockTradeRequest, opts ...grpc.CallOption) (*GetStockTradeResponse, error)
	// 获取基金交易
	GetFundTrade(ctx context.Context, in *GetFundTradeRequest, opts ...grpc.CallOption) (*GetFundTradeResponse, error)
	// 获取PI用户基本信息
	GetPIBasic(ctx context.Context, in *GetPIBasicRequest, opts ...grpc.CallOption) (*GetPIBasicResponse, error)
	// 获取PI用户行为
	GetPIBehavior(ctx context.Context, in *GetPIBehaviorRequest, opts ...grpc.CallOption) (*GetPIBehaviorResponse, error)
	// 获取开户流程
	GetAccountProcess(ctx context.Context, in *GetAccountProcessRequest, opts ...grpc.CallOption) (*GetAccountProcessResponse, error)
	// 获取开户异常
	GetAccountException(ctx context.Context, in *GetAccountExceptionRequest, opts ...grpc.CallOption) (*GetAccountExceptionResponse, error)
	// 获取IPO认购情况
	GetIPOSubscription(ctx context.Context, in *GetIPOSubscriptionRequest, opts ...grpc.CallOption) (*GetIPOSubscriptionResponse, error)
	// 获取IPO分析
	GetIPOAnaalysis(ctx context.Context, in *GetIPOAnaalysisRequest, opts ...grpc.CallOption) (*GetIPOAnaalysisResponse, error)
	// 获取客户融资情况
	GetFinanceCustomer(ctx context.Context, in *GetFinanceCustomerRequest, opts ...grpc.CallOption) (*GetFinanceCustomerResponse, error)
	// 获取热门股票融资情况
	GetFinanceStock(ctx context.Context, in *GetFinanceStockRequest, opts ...grpc.CallOption) (*GetFinanceStockResponse, error)
	// 获取明细数据
	GetDrilldownDetail(ctx context.Context, in *GetDrilldownDetailRequest, opts ...grpc.CallOption) (*GetDrilldownDetailResponse, error)
	// 获取历史趋势数据
	GetDrilldownTrend(ctx context.Context, in *GetDrilldownTrendRequest, opts ...grpc.CallOption) (*GetDrilldownTrendResponse, error)
	// 用户登录
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// 获取用户信息
	GetAuthInfo(ctx context.Context, in *GetAuthInfoRequest, opts ...grpc.CallOption) (*GetAuthInfoResponse, error)
}

type dashboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDashboardServiceClient(cc grpc.ClientConnInterface) DashboardServiceClient {
	return &dashboardServiceClient{cc}
}

func (c *dashboardServiceClient) GetCoreIndicators(ctx context.Context, in *GetCoreIndicatorsRequest, opts ...grpc.CallOption) (*GetCoreIndicatorsResponse, error) {
	out := new(GetCoreIndicatorsResponse)
	err := c.cc.Invoke(ctx, "/dashboard.DashboardService/GetCoreIndicators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetPerformance(ctx context.Context, in *GetPerformanceRequest, opts ...grpc.CallOption) (*GetPerformanceResponse, error) {
	out := new(GetPerformanceResponse)
	err := c.cc.Invoke(ctx, "/dashboard.DashboardService/GetPerformance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetCustomerDistribution(ctx context.Context, in *GetCustomerDistributionRequest, opts ...grpc.CallOption) (*GetCustomerDistributionResponse, error) {
	out := new(GetCustomerDistributionResponse)
	err := c.cc.Invoke(ctx, "/dashboard.DashboardService/GetCustomerDistribution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetCustomerBehavior(ctx context.Context, in *GetCustomerBehaviorRequest, opts ...grpc.CallOption) (*GetCustomerBehaviorResponse, error) {
	out := new(GetCustomerBehaviorResponse)
	err := c.cc.Invoke(ctx, "/dashboard.DashboardService/GetCustomerBehavior", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetStockTrade(ctx context.Context, in *GetStockTradeRequest, opts ...grpc.CallOption) (*GetStockTradeResponse, error) {
	out := new(GetStockTradeResponse)
	err := c.cc.Invoke(ctx, "/dashboard.DashboardService/GetStockTrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetFundTrade(ctx context.Context, in *GetFundTradeRequest, opts ...grpc.CallOption) (*GetFundTradeResponse, error) {
	out := new(GetFundTradeResponse)
	err := c.cc.Invoke(ctx, "/dashboard.DashboardService/GetFundTrade", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetPIBasic(ctx context.Context, in *GetPIBasicRequest, opts ...grpc.CallOption) (*GetPIBasicResponse, error) {
	out := new(GetPIBasicResponse)
	err := c.cc.Invoke(ctx, "/dashboard.DashboardService/GetPIBasic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetPIBehavior(ctx context.Context, in *GetPIBehaviorRequest, opts ...grpc.CallOption) (*GetPIBehaviorResponse, error) {
	out := new(GetPIBehaviorResponse)
	err := c.cc.Invoke(ctx, "/dashboard.DashboardService/GetPIBehavior", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetAccountProcess(ctx context.Context, in *GetAccountProcessRequest, opts ...grpc.CallOption) (*GetAccountProcessResponse, error) {
	out := new(GetAccountProcessResponse)
	err := c.cc.Invoke(ctx, "/dashboard.DashboardService/GetAccountProcess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetAccountException(ctx context.Context, in *GetAccountExceptionRequest, opts ...grpc.CallOption) (*GetAccountExceptionResponse, error) {
	out := new(GetAccountExceptionResponse)
	err := c.cc.Invoke(ctx, "/dashboard.DashboardService/GetAccountException", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetIPOSubscription(ctx context.Context, in *GetIPOSubscriptionRequest, opts ...grpc.CallOption) (*GetIPOSubscriptionResponse, error) {
	out := new(GetIPOSubscriptionResponse)
	err := c.cc.Invoke(ctx, "/dashboard.DashboardService/GetIPOSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetIPOAnaalysis(ctx context.Context, in *GetIPOAnaalysisRequest, opts ...grpc.CallOption) (*GetIPOAnaalysisResponse, error) {
	out := new(GetIPOAnaalysisResponse)
	err := c.cc.Invoke(ctx, "/dashboard.DashboardService/GetIPOAnaalysis", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetFinanceCustomer(ctx context.Context, in *GetFinanceCustomerRequest, opts ...grpc.CallOption) (*GetFinanceCustomerResponse, error) {
	out := new(GetFinanceCustomerResponse)
	err := c.cc.Invoke(ctx, "/dashboard.DashboardService/GetFinanceCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetFinanceStock(ctx context.Context, in *GetFinanceStockRequest, opts ...grpc.CallOption) (*GetFinanceStockResponse, error) {
	out := new(GetFinanceStockResponse)
	err := c.cc.Invoke(ctx, "/dashboard.DashboardService/GetFinanceStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDrilldownDetail(ctx context.Context, in *GetDrilldownDetailRequest, opts ...grpc.CallOption) (*GetDrilldownDetailResponse, error) {
	out := new(GetDrilldownDetailResponse)
	err := c.cc.Invoke(ctx, "/dashboard.DashboardService/GetDrilldownDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetDrilldownTrend(ctx context.Context, in *GetDrilldownTrendRequest, opts ...grpc.CallOption) (*GetDrilldownTrendResponse, error) {
	out := new(GetDrilldownTrendResponse)
	err := c.cc.Invoke(ctx, "/dashboard.DashboardService/GetDrilldownTrend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/dashboard.DashboardService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetAuthInfo(ctx context.Context, in *GetAuthInfoRequest, opts ...grpc.CallOption) (*GetAuthInfoResponse, error) {
	out := new(GetAuthInfoResponse)
	err := c.cc.Invoke(ctx, "/dashboard.DashboardService/GetAuthInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DashboardServiceServer is the server API for DashboardService service.
// All implementations must embed UnimplementedDashboardServiceServer
// for forward compatibility
type DashboardServiceServer interface {
	// 获取核心指标
	GetCoreIndicators(context.Context, *GetCoreIndicatorsRequest) (*GetCoreIndicatorsResponse, error)
	// 获取业绩表现
	GetPerformance(context.Context, *GetPerformanceRequest) (*GetPerformanceResponse, error)
	// 获取客户分布
	GetCustomerDistribution(context.Context, *GetCustomerDistributionRequest) (*GetCustomerDistributionResponse, error)
	// 获取客户行为
	GetCustomerBehavior(context.Context, *GetCustomerBehaviorRequest) (*GetCustomerBehaviorResponse, error)
	// 获取股票交易
	GetStockTrade(context.Context, *GetStockTradeRequest) (*GetStockTradeResponse, error)
	// 获取基金交易
	GetFundTrade(context.Context, *GetFundTradeRequest) (*GetFundTradeResponse, error)
	// 获取PI用户基本信息
	GetPIBasic(context.Context, *GetPIBasicRequest) (*GetPIBasicResponse, error)
	// 获取PI用户行为
	GetPIBehavior(context.Context, *GetPIBehaviorRequest) (*GetPIBehaviorResponse, error)
	// 获取开户流程
	GetAccountProcess(context.Context, *GetAccountProcessRequest) (*GetAccountProcessResponse, error)
	// 获取开户异常
	GetAccountException(context.Context, *GetAccountExceptionRequest) (*GetAccountExceptionResponse, error)
	// 获取IPO认购情况
	GetIPOSubscription(context.Context, *GetIPOSubscriptionRequest) (*GetIPOSubscriptionResponse, error)
	// 获取IPO分析
	GetIPOAnaalysis(context.Context, *GetIPOAnaalysisRequest) (*GetIPOAnaalysisResponse, error)
	// 获取客户融资情况
	GetFinanceCustomer(context.Context, *GetFinanceCustomerRequest) (*GetFinanceCustomerResponse, error)
	// 获取热门股票融资情况
	GetFinanceStock(context.Context, *GetFinanceStockRequest) (*GetFinanceStockResponse, error)
	// 获取明细数据
	GetDrilldownDetail(context.Context, *GetDrilldownDetailRequest) (*GetDrilldownDetailResponse, error)
	// 获取历史趋势数据
	GetDrilldownTrend(context.Context, *GetDrilldownTrendRequest) (*GetDrilldownTrendResponse, error)
	// 用户登录
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// 获取用户信息
	GetAuthInfo(context.Context, *GetAuthInfoRequest) (*GetAuthInfoResponse, error)
	mustEmbedUnimplementedDashboardServiceServer()
}

// UnimplementedDashboardServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDashboardServiceServer struct {
}

func (UnimplementedDashboardServiceServer) GetCoreIndicators(context.Context, *GetCoreIndicatorsRequest) (*GetCoreIndicatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCoreIndicators not implemented")
}
func (UnimplementedDashboardServiceServer) GetPerformance(context.Context, *GetPerformanceRequest) (*GetPerformanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPerformance not implemented")
}
func (UnimplementedDashboardServiceServer) GetCustomerDistribution(context.Context, *GetCustomerDistributionRequest) (*GetCustomerDistributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerDistribution not implemented")
}
func (UnimplementedDashboardServiceServer) GetCustomerBehavior(context.Context, *GetCustomerBehaviorRequest) (*GetCustomerBehaviorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerBehavior not implemented")
}
func (UnimplementedDashboardServiceServer) GetStockTrade(context.Context, *GetStockTradeRequest) (*GetStockTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStockTrade not implemented")
}
func (UnimplementedDashboardServiceServer) GetFundTrade(context.Context, *GetFundTradeRequest) (*GetFundTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFundTrade not implemented")
}
func (UnimplementedDashboardServiceServer) GetPIBasic(context.Context, *GetPIBasicRequest) (*GetPIBasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPIBasic not implemented")
}
func (UnimplementedDashboardServiceServer) GetPIBehavior(context.Context, *GetPIBehaviorRequest) (*GetPIBehaviorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPIBehavior not implemented")
}
func (UnimplementedDashboardServiceServer) GetAccountProcess(context.Context, *GetAccountProcessRequest) (*GetAccountProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountProcess not implemented")
}
func (UnimplementedDashboardServiceServer) GetAccountException(context.Context, *GetAccountExceptionRequest) (*GetAccountExceptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountException not implemented")
}
func (UnimplementedDashboardServiceServer) GetIPOSubscription(context.Context, *GetIPOSubscriptionRequest) (*GetIPOSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIPOSubscription not implemented")
}
func (UnimplementedDashboardServiceServer) GetIPOAnaalysis(context.Context, *GetIPOAnaalysisRequest) (*GetIPOAnaalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIPOAnaalysis not implemented")
}
func (UnimplementedDashboardServiceServer) GetFinanceCustomer(context.Context, *GetFinanceCustomerRequest) (*GetFinanceCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFinanceCustomer not implemented")
}
func (UnimplementedDashboardServiceServer) GetFinanceStock(context.Context, *GetFinanceStockRequest) (*GetFinanceStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFinanceStock not implemented")
}
func (UnimplementedDashboardServiceServer) GetDrilldownDetail(context.Context, *GetDrilldownDetailRequest) (*GetDrilldownDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDrilldownDetail not implemented")
}
func (UnimplementedDashboardServiceServer) GetDrilldownTrend(context.Context, *GetDrilldownTrendRequest) (*GetDrilldownTrendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDrilldownTrend not implemented")
}
func (UnimplementedDashboardServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedDashboardServiceServer) GetAuthInfo(context.Context, *GetAuthInfoRequest) (*GetAuthInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthInfo not implemented")
}
func (UnimplementedDashboardServiceServer) mustEmbedUnimplementedDashboardServiceServer() {}

// UnsafeDashboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DashboardServiceServer will
// result in compilation errors.
type UnsafeDashboardServiceServer interface {
	mustEmbedUnimplementedDashboardServiceServer()
}

func RegisterDashboardServiceServer(s grpc.ServiceRegistrar, srv DashboardServiceServer) {
	s.RegisterService(&DashboardService_ServiceDesc, srv)
}

func _DashboardService_GetCoreIndicators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoreIndicatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetCoreIndicators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.DashboardService/GetCoreIndicators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetCoreIndicators(ctx, req.(*GetCoreIndicatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.DashboardService/GetPerformance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetPerformance(ctx, req.(*GetPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetCustomerDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerDistributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetCustomerDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.DashboardService/GetCustomerDistribution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetCustomerDistribution(ctx, req.(*GetCustomerDistributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetCustomerBehavior_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerBehaviorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetCustomerBehavior(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.DashboardService/GetCustomerBehavior",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetCustomerBehavior(ctx, req.(*GetCustomerBehaviorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetStockTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetStockTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.DashboardService/GetStockTrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetStockTrade(ctx, req.(*GetStockTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetFundTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFundTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetFundTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.DashboardService/GetFundTrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetFundTrade(ctx, req.(*GetFundTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetPIBasic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPIBasicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetPIBasic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.DashboardService/GetPIBasic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetPIBasic(ctx, req.(*GetPIBasicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetPIBehavior_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPIBehaviorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetPIBehavior(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.DashboardService/GetPIBehavior",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetPIBehavior(ctx, req.(*GetPIBehaviorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetAccountProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetAccountProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.DashboardService/GetAccountProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetAccountProcess(ctx, req.(*GetAccountProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetAccountException_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountExceptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetAccountException(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.DashboardService/GetAccountException",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetAccountException(ctx, req.(*GetAccountExceptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetIPOSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIPOSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetIPOSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.DashboardService/GetIPOSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetIPOSubscription(ctx, req.(*GetIPOSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetIPOAnaalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIPOAnaalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetIPOAnaalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.DashboardService/GetIPOAnaalysis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetIPOAnaalysis(ctx, req.(*GetIPOAnaalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetFinanceCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFinanceCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetFinanceCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.DashboardService/GetFinanceCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetFinanceCustomer(ctx, req.(*GetFinanceCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetFinanceStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFinanceStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetFinanceStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.DashboardService/GetFinanceStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetFinanceStock(ctx, req.(*GetFinanceStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDrilldownDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDrilldownDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDrilldownDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.DashboardService/GetDrilldownDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDrilldownDetail(ctx, req.(*GetDrilldownDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetDrilldownTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDrilldownTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDrilldownTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.DashboardService/GetDrilldownTrend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDrilldownTrend(ctx, req.(*GetDrilldownTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.DashboardService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetAuthInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetAuthInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.DashboardService/GetAuthInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetAuthInfo(ctx, req.(*GetAuthInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DashboardService_ServiceDesc is the grpc.ServiceDesc for DashboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DashboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dashboard.DashboardService",
	HandlerType: (*DashboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCoreIndicators",
			Handler:    _DashboardService_GetCoreIndicators_Handler,
		},
		{
			MethodName: "GetPerformance",
			Handler:    _DashboardService_GetPerformance_Handler,
		},
		{
			MethodName: "GetCustomerDistribution",
			Handler:    _DashboardService_GetCustomerDistribution_Handler,
		},
		{
			MethodName: "GetCustomerBehavior",
			Handler:    _DashboardService_GetCustomerBehavior_Handler,
		},
		{
			MethodName: "GetStockTrade",
			Handler:    _DashboardService_GetStockTrade_Handler,
		},
		{
			MethodName: "GetFundTrade",
			Handler:    _DashboardService_GetFundTrade_Handler,
		},
		{
			MethodName: "GetPIBasic",
			Handler:    _DashboardService_GetPIBasic_Handler,
		},
		{
			MethodName: "GetPIBehavior",
			Handler:    _DashboardService_GetPIBehavior_Handler,
		},
		{
			MethodName: "GetAccountProcess",
			Handler:    _DashboardService_GetAccountProcess_Handler,
		},
		{
			MethodName: "GetAccountException",
			Handler:    _DashboardService_GetAccountException_Handler,
		},
		{
			MethodName: "GetIPOSubscription",
			Handler:    _DashboardService_GetIPOSubscription_Handler,
		},
		{
			MethodName: "GetIPOAnaalysis",
			Handler:    _DashboardService_GetIPOAnaalysis_Handler,
		},
		{
			MethodName: "GetFinanceCustomer",
			Handler:    _DashboardService_GetFinanceCustomer_Handler,
		},
		{
			MethodName: "GetFinanceStock",
			Handler:    _DashboardService_GetFinanceStock_Handler,
		},
		{
			MethodName: "GetDrilldownDetail",
			Handler:    _DashboardService_GetDrilldownDetail_Handler,
		},
		{
			MethodName: "GetDrilldownTrend",
			Handler:    _DashboardService_GetDrilldownTrend_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _DashboardService_Login_Handler,
		},
		{
			MethodName: "GetAuthInfo",
			Handler:    _DashboardService_GetAuthInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dashboard.proto",
}
