// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.1
// source: internal/grpc/proto/dashboard.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DashboardService_GetCoreIndicators_FullMethodName = "/dashboard.DashboardService/GetCoreIndicators"
	DashboardService_GetPerformance_FullMethodName    = "/dashboard.DashboardService/GetPerformance"
)

// DashboardServiceClient is the client API for DashboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DashboardServiceClient interface {
	// 获取核心指标
	GetCoreIndicators(ctx context.Context, in *GetCoreIndicatorsRequest, opts ...grpc.CallOption) (*GetCoreIndicatorsResponse, error)
	// 获取业绩表现
	GetPerformance(ctx context.Context, in *GetPerformanceRequest, opts ...grpc.CallOption) (*GetPerformanceResponse, error)
}

type dashboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDashboardServiceClient(cc grpc.ClientConnInterface) DashboardServiceClient {
	return &dashboardServiceClient{cc}
}

func (c *dashboardServiceClient) GetCoreIndicators(ctx context.Context, in *GetCoreIndicatorsRequest, opts ...grpc.CallOption) (*GetCoreIndicatorsResponse, error) {
	out := new(GetCoreIndicatorsResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetCoreIndicators_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetPerformance(ctx context.Context, in *GetPerformanceRequest, opts ...grpc.CallOption) (*GetPerformanceResponse, error) {
	out := new(GetPerformanceResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetPerformance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DashboardServiceServer is the server API for DashboardService service.
// All implementations must embed UnimplementedDashboardServiceServer
// for forward compatibility
type DashboardServiceServer interface {
	// 获取核心指标
	GetCoreIndicators(context.Context, *GetCoreIndicatorsRequest) (*GetCoreIndicatorsResponse, error)
	// 获取业绩表现
	GetPerformance(context.Context, *GetPerformanceRequest) (*GetPerformanceResponse, error)
	mustEmbedUnimplementedDashboardServiceServer()
}

// UnimplementedDashboardServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDashboardServiceServer struct {
}

func (UnimplementedDashboardServiceServer) GetCoreIndicators(context.Context, *GetCoreIndicatorsRequest) (*GetCoreIndicatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCoreIndicators not implemented")
}
func (UnimplementedDashboardServiceServer) GetPerformance(context.Context, *GetPerformanceRequest) (*GetPerformanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPerformance not implemented")
}
func (UnimplementedDashboardServiceServer) mustEmbedUnimplementedDashboardServiceServer() {}

// UnsafeDashboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DashboardServiceServer will
// result in compilation errors.
type UnsafeDashboardServiceServer interface {
	mustEmbedUnimplementedDashboardServiceServer()
}

func RegisterDashboardServiceServer(s grpc.ServiceRegistrar, srv DashboardServiceServer) {
	s.RegisterService(&DashboardService_ServiceDesc, srv)
}

func _DashboardService_GetCoreIndicators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoreIndicatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetCoreIndicators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetCoreIndicators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetCoreIndicators(ctx, req.(*GetCoreIndicatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetPerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetPerformance(ctx, req.(*GetPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DashboardService_ServiceDesc is the grpc.ServiceDesc for DashboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DashboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dashboard.DashboardService",
	HandlerType: (*DashboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCoreIndicators",
			Handler:    _DashboardService_GetCoreIndicators_Handler,
		},
		{
			MethodName: "GetPerformance",
			Handler:    _DashboardService_GetPerformance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/proto/dashboard.proto",
}
