// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/grpc/proto/dashboard.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求和响应消息
type GetCoreIndicatorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"` // 统计周期
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoreIndicatorsRequest) Reset() {
	*x = GetCoreIndicatorsRequest{}
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoreIndicatorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoreIndicatorsRequest) ProtoMessage() {}

func (x *GetCoreIndicatorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoreIndicatorsRequest.ProtoReflect.Descriptor instead.
func (*GetCoreIndicatorsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *GetCoreIndicatorsRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetCoreIndicatorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *CoreIndicators        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoreIndicatorsResponse) Reset() {
	*x = GetCoreIndicatorsResponse{}
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoreIndicatorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoreIndicatorsResponse) ProtoMessage() {}

func (x *GetCoreIndicatorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoreIndicatorsResponse.ProtoReflect.Descriptor instead.
func (*GetCoreIndicatorsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *GetCoreIndicatorsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCoreIndicatorsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCoreIndicatorsResponse) GetData() *CoreIndicators {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetPerformanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"` // 统计周期
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPerformanceRequest) Reset() {
	*x = GetPerformanceRequest{}
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPerformanceRequest) ProtoMessage() {}

func (x *GetPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerformanceRequest.ProtoReflect.Descriptor instead.
func (*GetPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *GetPerformanceRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetPerformanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Performance           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPerformanceResponse) Reset() {
	*x = GetPerformanceResponse{}
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPerformanceResponse) ProtoMessage() {}

func (x *GetPerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerformanceResponse.ProtoReflect.Descriptor instead.
func (*GetPerformanceResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *GetPerformanceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPerformanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPerformanceResponse) GetData() *Performance {
	if x != nil {
		return x.Data
	}
	return nil
}

// 数据结构
type CoreIndicators struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RegisteredUsers  *Indicator             `protobuf:"bytes,1,opt,name=registered_users,json=registeredUsers,proto3" json:"registered_users,omitempty"`
	AccountCount     *Indicator             `protobuf:"bytes,2,opt,name=account_count,json=accountCount,proto3" json:"account_count,omitempty"`
	ActiveUsers      *Indicator             `protobuf:"bytes,3,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	DepositUsers     *Indicator             `protobuf:"bytes,4,opt,name=deposit_users,json=depositUsers,proto3" json:"deposit_users,omitempty"`
	DepositAmount    *Indicator             `protobuf:"bytes,5,opt,name=deposit_amount,json=depositAmount,proto3" json:"deposit_amount,omitempty"`
	StockTradeUsers  *Indicator             `protobuf:"bytes,6,opt,name=stock_trade_users,json=stockTradeUsers,proto3" json:"stock_trade_users,omitempty"`
	StockTradeAmount *Indicator             `protobuf:"bytes,7,opt,name=stock_trade_amount,json=stockTradeAmount,proto3" json:"stock_trade_amount,omitempty"`
	FundTradeUsers   *Indicator             `protobuf:"bytes,8,opt,name=fund_trade_users,json=fundTradeUsers,proto3" json:"fund_trade_users,omitempty"`
	FundTradeAmount  *Indicator             `protobuf:"bytes,9,opt,name=fund_trade_amount,json=fundTradeAmount,proto3" json:"fund_trade_amount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CoreIndicators) Reset() {
	*x = CoreIndicators{}
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreIndicators) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreIndicators) ProtoMessage() {}

func (x *CoreIndicators) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreIndicators.ProtoReflect.Descriptor instead.
func (*CoreIndicators) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *CoreIndicators) GetRegisteredUsers() *Indicator {
	if x != nil {
		return x.RegisteredUsers
	}
	return nil
}

func (x *CoreIndicators) GetAccountCount() *Indicator {
	if x != nil {
		return x.AccountCount
	}
	return nil
}

func (x *CoreIndicators) GetActiveUsers() *Indicator {
	if x != nil {
		return x.ActiveUsers
	}
	return nil
}

func (x *CoreIndicators) GetDepositUsers() *Indicator {
	if x != nil {
		return x.DepositUsers
	}
	return nil
}

func (x *CoreIndicators) GetDepositAmount() *Indicator {
	if x != nil {
		return x.DepositAmount
	}
	return nil
}

func (x *CoreIndicators) GetStockTradeUsers() *Indicator {
	if x != nil {
		return x.StockTradeUsers
	}
	return nil
}

func (x *CoreIndicators) GetStockTradeAmount() *Indicator {
	if x != nil {
		return x.StockTradeAmount
	}
	return nil
}

func (x *CoreIndicators) GetFundTradeUsers() *Indicator {
	if x != nil {
		return x.FundTradeUsers
	}
	return nil
}

func (x *CoreIndicators) GetFundTradeAmount() *Indicator {
	if x != nil {
		return x.FundTradeAmount
	}
	return nil
}

type Indicator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Change        int32                  `protobuf:"varint,2,opt,name=change,proto3" json:"change,omitempty"`
	ChangeRate    float64                `protobuf:"fixed64,3,opt,name=change_rate,json=changeRate,proto3" json:"change_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Indicator) Reset() {
	*x = Indicator{}
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Indicator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Indicator) ProtoMessage() {}

func (x *Indicator) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Indicator.ProtoReflect.Descriptor instead.
func (*Indicator) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dashboard_proto_rawDescGZIP(), []int{5}
}

func (x *Indicator) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Indicator) GetChange() int32 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *Indicator) GetChangeRate() float64 {
	if x != nil {
		return x.ChangeRate
	}
	return 0
}

type Performance struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	StockRevenue           int32                  `protobuf:"varint,1,opt,name=stock_revenue,json=stockRevenue,proto3" json:"stock_revenue,omitempty"`
	FundRevenue            int32                  `protobuf:"varint,2,opt,name=fund_revenue,json=fundRevenue,proto3" json:"fund_revenue,omitempty"`
	RevenueStructure       []*RevenueItem         `protobuf:"bytes,3,rep,name=revenue_structure,json=revenueStructure,proto3" json:"revenue_structure,omitempty"`
	RevenueTrend           []*RevenueTrend        `protobuf:"bytes,4,rep,name=revenue_trend,json=revenueTrend,proto3" json:"revenue_trend,omitempty"`
	RevenueChange          *RevenueChange         `protobuf:"bytes,5,opt,name=revenue_change,json=revenueChange,proto3" json:"revenue_change,omitempty"`
	DepositNetGrowth       int32                  `protobuf:"varint,6,opt,name=deposit_net_growth,json=depositNetGrowth,proto3" json:"deposit_net_growth,omitempty"`
	DepositTrend           []*DepositTrend        `protobuf:"bytes,7,rep,name=deposit_trend,json=depositTrend,proto3" json:"deposit_trend,omitempty"`
	DepositWithdrawalRatio float64                `protobuf:"fixed64,8,opt,name=deposit_withdrawal_ratio,json=depositWithdrawalRatio,proto3" json:"deposit_withdrawal_ratio,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Performance) Reset() {
	*x = Performance{}
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Performance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Performance) ProtoMessage() {}

func (x *Performance) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Performance.ProtoReflect.Descriptor instead.
func (*Performance) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dashboard_proto_rawDescGZIP(), []int{6}
}

func (x *Performance) GetStockRevenue() int32 {
	if x != nil {
		return x.StockRevenue
	}
	return 0
}

func (x *Performance) GetFundRevenue() int32 {
	if x != nil {
		return x.FundRevenue
	}
	return 0
}

func (x *Performance) GetRevenueStructure() []*RevenueItem {
	if x != nil {
		return x.RevenueStructure
	}
	return nil
}

func (x *Performance) GetRevenueTrend() []*RevenueTrend {
	if x != nil {
		return x.RevenueTrend
	}
	return nil
}

func (x *Performance) GetRevenueChange() *RevenueChange {
	if x != nil {
		return x.RevenueChange
	}
	return nil
}

func (x *Performance) GetDepositNetGrowth() int32 {
	if x != nil {
		return x.DepositNetGrowth
	}
	return 0
}

func (x *Performance) GetDepositTrend() []*DepositTrend {
	if x != nil {
		return x.DepositTrend
	}
	return nil
}

func (x *Performance) GetDepositWithdrawalRatio() float64 {
	if x != nil {
		return x.DepositWithdrawalRatio
	}
	return 0
}

type RevenueItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevenueItem) Reset() {
	*x = RevenueItem{}
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevenueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevenueItem) ProtoMessage() {}

func (x *RevenueItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevenueItem.ProtoReflect.Descriptor instead.
func (*RevenueItem) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dashboard_proto_rawDescGZIP(), []int{7}
}

func (x *RevenueItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RevenueItem) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type RevenueTrend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	Stock         int32                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	Fund          int32                  `protobuf:"varint,3,opt,name=fund,proto3" json:"fund,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevenueTrend) Reset() {
	*x = RevenueTrend{}
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevenueTrend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevenueTrend) ProtoMessage() {}

func (x *RevenueTrend) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevenueTrend.ProtoReflect.Descriptor instead.
func (*RevenueTrend) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dashboard_proto_rawDescGZIP(), []int{8}
}

func (x *RevenueTrend) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *RevenueTrend) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *RevenueTrend) GetFund() int32 {
	if x != nil {
		return x.Fund
	}
	return 0
}

type RevenueChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Yoy           float64                `protobuf:"fixed64,1,opt,name=yoy,proto3" json:"yoy,omitempty"`
	Mom           float64                `protobuf:"fixed64,2,opt,name=mom,proto3" json:"mom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevenueChange) Reset() {
	*x = RevenueChange{}
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevenueChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevenueChange) ProtoMessage() {}

func (x *RevenueChange) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevenueChange.ProtoReflect.Descriptor instead.
func (*RevenueChange) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dashboard_proto_rawDescGZIP(), []int{9}
}

func (x *RevenueChange) GetYoy() float64 {
	if x != nil {
		return x.Yoy
	}
	return 0
}

func (x *RevenueChange) GetMom() float64 {
	if x != nil {
		return x.Mom
	}
	return 0
}

type DepositTrend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositTrend) Reset() {
	*x = DepositTrend{}
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositTrend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositTrend) ProtoMessage() {}

func (x *DepositTrend) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_dashboard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositTrend.ProtoReflect.Descriptor instead.
func (*DepositTrend) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_dashboard_proto_rawDescGZIP(), []int{10}
}

func (x *DepositTrend) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *DepositTrend) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_internal_grpc_proto_dashboard_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_dashboard_proto_rawDesc = "" +
	"\n" +
	"#internal/grpc/proto/dashboard.proto\x12\tdashboard\"2\n" +
	"\x18GetCoreIndicatorsRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\"x\n" +
	"\x19GetCoreIndicatorsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.dashboard.CoreIndicatorsR\x04data\"/\n" +
	"\x15GetPerformanceRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\"r\n" +
	"\x16GetPerformanceResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x04data\x18\x03 \x01(\v2\x16.dashboard.PerformanceR\x04data\"\xc5\x04\n" +
	"\x0eCoreIndicators\x12?\n" +
	"\x10registered_users\x18\x01 \x01(\v2\x14.dashboard.IndicatorR\x0fregisteredUsers\x129\n" +
	"\raccount_count\x18\x02 \x01(\v2\x14.dashboard.IndicatorR\faccountCount\x127\n" +
	"\factive_users\x18\x03 \x01(\v2\x14.dashboard.IndicatorR\vactiveUsers\x129\n" +
	"\rdeposit_users\x18\x04 \x01(\v2\x14.dashboard.IndicatorR\fdepositUsers\x12;\n" +
	"\x0edeposit_amount\x18\x05 \x01(\v2\x14.dashboard.IndicatorR\rdepositAmount\x12@\n" +
	"\x11stock_trade_users\x18\x06 \x01(\v2\x14.dashboard.IndicatorR\x0fstockTradeUsers\x12B\n" +
	"\x12stock_trade_amount\x18\a \x01(\v2\x14.dashboard.IndicatorR\x10stockTradeAmount\x12>\n" +
	"\x10fund_trade_users\x18\b \x01(\v2\x14.dashboard.IndicatorR\x0efundTradeUsers\x12@\n" +
	"\x11fund_trade_amount\x18\t \x01(\v2\x14.dashboard.IndicatorR\x0ffundTradeAmount\"Z\n" +
	"\tIndicator\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x16\n" +
	"\x06change\x18\x02 \x01(\x05R\x06change\x12\x1f\n" +
	"\vchange_rate\x18\x03 \x01(\x01R\n" +
	"changeRate\"\xbf\x03\n" +
	"\vPerformance\x12#\n" +
	"\rstock_revenue\x18\x01 \x01(\x05R\fstockRevenue\x12!\n" +
	"\ffund_revenue\x18\x02 \x01(\x05R\vfundRevenue\x12C\n" +
	"\x11revenue_structure\x18\x03 \x03(\v2\x16.dashboard.RevenueItemR\x10revenueStructure\x12<\n" +
	"\rrevenue_trend\x18\x04 \x03(\v2\x17.dashboard.RevenueTrendR\frevenueTrend\x12?\n" +
	"\x0erevenue_change\x18\x05 \x01(\v2\x18.dashboard.RevenueChangeR\rrevenueChange\x12,\n" +
	"\x12deposit_net_growth\x18\x06 \x01(\x05R\x10depositNetGrowth\x12<\n" +
	"\rdeposit_trend\x18\a \x03(\v2\x17.dashboard.DepositTrendR\fdepositTrend\x128\n" +
	"\x18deposit_withdrawal_ratio\x18\b \x01(\x01R\x16depositWithdrawalRatio\"7\n" +
	"\vRevenueItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"N\n" +
	"\fRevenueTrend\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x05R\x05stock\x12\x12\n" +
	"\x04fund\x18\x03 \x01(\x05R\x04fund\"3\n" +
	"\rRevenueChange\x12\x10\n" +
	"\x03yoy\x18\x01 \x01(\x01R\x03yoy\x12\x10\n" +
	"\x03mom\x18\x02 \x01(\x01R\x03mom\":\n" +
	"\fDepositTrend\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value2\xcd\x01\n" +
	"\x10DashboardService\x12`\n" +
	"\x11GetCoreIndicators\x12#.dashboard.GetCoreIndicatorsRequest\x1a$.dashboard.GetCoreIndicatorsResponse\"\x00\x12W\n" +
	"\x0eGetPerformance\x12 .dashboard.GetPerformanceRequest\x1a!.dashboard.GetPerformanceResponse\"\x00B$Z\"dashboard-data/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_dashboard_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_dashboard_proto_rawDescData []byte
)

func file_internal_grpc_proto_dashboard_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_dashboard_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_dashboard_proto_rawDesc), len(file_internal_grpc_proto_dashboard_proto_rawDesc)))
	})
	return file_internal_grpc_proto_dashboard_proto_rawDescData
}

var file_internal_grpc_proto_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_grpc_proto_dashboard_proto_goTypes = []any{
	(*GetCoreIndicatorsRequest)(nil),  // 0: dashboard.GetCoreIndicatorsRequest
	(*GetCoreIndicatorsResponse)(nil), // 1: dashboard.GetCoreIndicatorsResponse
	(*GetPerformanceRequest)(nil),     // 2: dashboard.GetPerformanceRequest
	(*GetPerformanceResponse)(nil),    // 3: dashboard.GetPerformanceResponse
	(*CoreIndicators)(nil),            // 4: dashboard.CoreIndicators
	(*Indicator)(nil),                 // 5: dashboard.Indicator
	(*Performance)(nil),               // 6: dashboard.Performance
	(*RevenueItem)(nil),               // 7: dashboard.RevenueItem
	(*RevenueTrend)(nil),              // 8: dashboard.RevenueTrend
	(*RevenueChange)(nil),             // 9: dashboard.RevenueChange
	(*DepositTrend)(nil),              // 10: dashboard.DepositTrend
}
var file_internal_grpc_proto_dashboard_proto_depIdxs = []int32{
	4,  // 0: dashboard.GetCoreIndicatorsResponse.data:type_name -> dashboard.CoreIndicators
	6,  // 1: dashboard.GetPerformanceResponse.data:type_name -> dashboard.Performance
	5,  // 2: dashboard.CoreIndicators.registered_users:type_name -> dashboard.Indicator
	5,  // 3: dashboard.CoreIndicators.account_count:type_name -> dashboard.Indicator
	5,  // 4: dashboard.CoreIndicators.active_users:type_name -> dashboard.Indicator
	5,  // 5: dashboard.CoreIndicators.deposit_users:type_name -> dashboard.Indicator
	5,  // 6: dashboard.CoreIndicators.deposit_amount:type_name -> dashboard.Indicator
	5,  // 7: dashboard.CoreIndicators.stock_trade_users:type_name -> dashboard.Indicator
	5,  // 8: dashboard.CoreIndicators.stock_trade_amount:type_name -> dashboard.Indicator
	5,  // 9: dashboard.CoreIndicators.fund_trade_users:type_name -> dashboard.Indicator
	5,  // 10: dashboard.CoreIndicators.fund_trade_amount:type_name -> dashboard.Indicator
	7,  // 11: dashboard.Performance.revenue_structure:type_name -> dashboard.RevenueItem
	8,  // 12: dashboard.Performance.revenue_trend:type_name -> dashboard.RevenueTrend
	9,  // 13: dashboard.Performance.revenue_change:type_name -> dashboard.RevenueChange
	10, // 14: dashboard.Performance.deposit_trend:type_name -> dashboard.DepositTrend
	0,  // 15: dashboard.DashboardService.GetCoreIndicators:input_type -> dashboard.GetCoreIndicatorsRequest
	2,  // 16: dashboard.DashboardService.GetPerformance:input_type -> dashboard.GetPerformanceRequest
	1,  // 17: dashboard.DashboardService.GetCoreIndicators:output_type -> dashboard.GetCoreIndicatorsResponse
	3,  // 18: dashboard.DashboardService.GetPerformance:output_type -> dashboard.GetPerformanceResponse
	17, // [17:19] is the sub-list for method output_type
	15, // [15:17] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_dashboard_proto_init() }
func file_internal_grpc_proto_dashboard_proto_init() {
	if File_internal_grpc_proto_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_dashboard_proto_rawDesc), len(file_internal_grpc_proto_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_dashboard_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_dashboard_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_dashboard_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_dashboard_proto = out.File
	file_internal_grpc_proto_dashboard_proto_goTypes = nil
	file_internal_grpc_proto_dashboard_proto_depIdxs = nil
}
